version: '3.9'
name: 'isdf_local'

services:
  isdf:
    image: isdf_local:latest
    container_name: isdf_local_cont
    build:
      context: ./
    environment:
      - DISPLAY
      - XAUTORITY
      - QT_X11_NO_MITSHM=1
    ipc: host
    stdin_open: true
    tty: true
    network_mode: host
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - ./lib/iSDF:/catkin_ws/src/iSDF
